#!/usr/bin/env bash
# Install and configure HAproxy


apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7 -y
apt-get install -y haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 54.80.197.65:80 check
    server web-02 54.157.160.175:80 check
EOF

service haproxy start 
