#!/usr/bin/env bash
# This script loop from 1 to 10 print bad luch for the forth, good luch for the 8th and Best school for the rest

i=1
while [ $i -le 10 ];
do 
	if [ $i = 4 ];
	then 
		echo "bad luck"
	elif [ $i = 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi;
	((i++))

done
