#!/usr/bin/env bash
# configure the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx


printf %s "server {
	 listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;
    }" >  /etc/nginx/sites-enabled/default

sudo service nginx restart
